Staff dashboard
converse-data-solutions/school_management pull request #12
Opened 2023-12-22 17:09 UTC by aravintsamy-converse

2023-12-23 05:41 UTC, aravindhan-converse approved these changes

2023-12-25 11:21 UTC, sivakumar-converse requested changes

2023-12-25 11:21 UTC, sivakumar-converse commented on app/controllers/parent/parent_attendance_views_controller.rb
> +class Parent::ParentAttendanceViewsController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
parent/parent_ not needed if you like to wrap use parents/attendance -> Give some meaningful name

2023-12-25 11:21 UTC, sivakumar-converse commented on app/controllers/parent/parent_notices_controller.rb
> +class Parent::ParentNoticesController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
same here use meaningful name

2023-12-25 11:21 UTC, sivakumar-converse commented on app/controllers/staff/staff_attendance_views_controller.rb
> +class Staff::StaffAttendanceViewsController < ApplicationController  # rubocop:disable Style/ClassAndModuleChildren
same here use meaningful name

2023-12-26 08:35 UTC, aravindhan-converse approved these changes

2023-12-26 09:38 UTC, aravindhan-converse approved these changes

2023-12-26 09:55 UTC, sivakumar-converse approved these changes

2023-12-26 10:13 UTC, merged